#!/usr/bin/env bash
set -eux

DOCKER=docker
FIXTURES_DIR=./fixtures

# Setup test fixtures

# first, remove the old fixtures
rm -rf ${FIXTURES_DIR}

# for tendermint

mkdir -p ${FIXTURES_DIR}/tendermint/ibc0
# retrieve the mnemonic from the container to the local
${DOCKER} cp tendermint-chain:/root/data/ibc0/key_seed.json  ${FIXTURES_DIR}/tendermint/ibc0/key_seed.json

# for harmony
mkdir -p ${FIXTURES_DIR}/harmony/contracts

# retrieve the mnemonic and files with contract address from the container to the local
#${DOCKER} cp harmony-chain:/root/mnemonic ${FIXTURES_DIR}/harmony/
${DOCKER} cp harmony-chain:/root/contracts ${FIXTURES_DIR}/harmony/

## generate a json file for Relayer configuration from a template file
IBCHostAddress=$(cat ${FIXTURES_DIR}/harmony/contracts/IBCHost)
IBCHandlerAddress=$(cat ${FIXTURES_DIR}/harmony/contracts/IBCHandler)

sed -e "s/\"ibc_host_address\": \"\"/\"ibc_host_address\": \"${IBCHostAddress}\"/" \
    -e "s/\"ibc_handler_address\": \"\"/\"ibc_handler_address\": \"${IBCHandlerAddress}\"/" \
    configs/tpl/ibc-1.json.tpl > configs/demo/ibc-1.json
