#!/usr/bin/env bash

set -eux

SCRIPT_DIR=$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)

. ${SCRIPT_DIR}/../../../scripts/util

## load harmony lib env
. ${SCRIPT_DIR}/env

RLY_BINARY=${SCRIPT_DIR}/../../../../relayer/build/uly
RLY="${RLY_BINARY} --debug"

CHAINID_ONE=ibc0
CHAINID_TWO=ibc1
RLYKEY=testkey
PATH_NAME=ibc01

# add a path between chain0 and chain1
$RLY paths add $CHAINID_ONE $CHAINID_TWO $PATH_NAME --file=./configs/path.json

retry 5 $RLY tx clients $PATH_NAME
retry 5 $RLY tx update-clients $PATH_NAME
retry 10 $RLY tx connection $PATH_NAME
retry 10 $RLY tx channel $PATH_NAME
