name: deploy ibc contracts on local harmony

on: [push, pull_request]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-20.04
    env:
      HARMONY_GAS_LIMIT: 100000000
      HARMONY_GAS_PRICE: 1000000000
      # cf. https://github.com/harmony-one/harmony/pull/3332
      HARMONY_LOCAL_PRIVATE_KEY: '0x1f84c95ac16e6a50f08d44c7bde7aff8742212fda6e4321fde48bf83bef266dc'
      HARMONY_LOCAL_SHARD_0_URL: http://localhost:9598
      HARMONY_LOCAL_SHARD_1_URL: http://localhost:9596
    steps:
      # go is needed for harmony
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Set up Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-deploy-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-deploy-${{ env.cache-name }}-
      - run: npm install
        working-directory: ./contract
      - name: Setup Harmony Debug Env
        run: |
          make setup-harmony
      - name: Compile contracts
        run: |
          make compile-contracts
      - name: Deploy contracts to shard0
        run: |
          make deploy-contracts-shard0
      - name: Deploy contracts to shard1
        run: |
          make deploy-contracts-shard1
